feat: improve error messages by using span info
Improve error messages for incorrect use of the API. Take advantage
spans of `compiler_error!` macro.

Move from:
```
error: proc-macro derive panicked
  --> src/main.rs:25:17
   |
25 | #[derive(Debug, TagName)]
   |                 ^^^^^^^
   |
   = help: message: `tag` attribute expectes an assignment expression `[tag(case = "lower" | "upper">]`
```

To this:
```
error: right handside of the assignment expression is expected to be a string literal "lower" or "upper"
  --> src/main.rs:27:18
   |
27 |     #[tag(case = 1)]
   |                  ^
```